import { createResourceApi } from '../api/admin'

/**
 * One entry per "plain" CRUD resource (the backend's admin_generic.php
 * counterpart) — the generic ResourceList/ResourceForm pages read this to
 * render a table and a form without a bespoke page per resource. Courses,
 * Knowledge Center content, and Learning Paths get their own dedicated
 * pages because they carry nested child data (curriculum, tags, steps)
 * a generic form can't express.
 */
export const RESOURCE_CONFIGS = {
  careers: {
    key: 'careers',
    label: 'Careers',
    singular: 'Career',
    apiBase: '/admin/careers',
    api: createResourceApi('/admin/careers'),
    permission: 'knowledge.manage',
    titleField: 'title',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'publish_status', label: 'Status', badge: true },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', hint: 'Leave blank to auto-generate from the title.' },
      { name: 'description', label: 'Role description', type: 'textarea', hint: 'What this role does day-to-day.' },
      { name: 'beginner_skills', label: 'Beginner skills', type: 'textarea', hint: 'Separate with semicolons.' },
      { name: 'intermediate_skills', label: 'Intermediate skills', type: 'textarea', hint: 'Separate with semicolons.' },
      { name: 'advanced_skills', label: 'Advanced skills', type: 'textarea', hint: 'Separate with semicolons.' },
      { name: 'tools', label: 'Tools', type: 'textarea', hint: 'Separate with semicolons.' },
      { name: 'roadmap_summary', label: 'Roadmap summary', type: 'text' },
      { name: 'career_progression', label: 'Career progression', type: 'textarea' },
      { name: 'publish_status', label: 'Status', type: 'select', options: ['draft', 'published'], default: 'draft' },
    ],
  },
  'learning-paths': {
    key: 'learning-paths',
    label: 'Learning Paths',
    singular: 'Learning Path',
    apiBase: '/admin/learning-paths',
    api: createResourceApi('/admin/learning-paths'),
    permission: 'knowledge.manage',
    titleField: 'title',
    hasSteps: true,
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'publish_status', label: 'Status', badge: true },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', hint: 'Leave blank to auto-generate from the title.' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'target_audience', label: 'Target audience', type: 'text' },
      { name: 'publish_status', label: 'Status', type: 'select', options: ['draft', 'published'], default: 'draft' },
    ],
  },
  certifications: {
    key: 'certifications',
    label: 'Certifications',
    singular: 'Certification',
    apiBase: '/admin/certifications',
    api: createResourceApi('/admin/certifications'),
    permission: 'knowledge.manage',
    titleField: 'name',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'level', label: 'Level' },
      { key: 'publish_status', label: 'Status', badge: true },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', hint: 'Leave blank to auto-generate from the name.' },
      { name: 'short_description', label: 'Short summary', type: 'textarea' },
      { name: 'body', label: 'Full description', type: 'textarea', rows: 6 },
      { name: 'level', label: 'Level', type: 'select', options: ['beginner', 'intermediate', 'advanced'], default: 'beginner' },
      { name: 'domain', label: 'Domain', type: 'text', hint: 'e.g. Governance, Risk & Compliance' },
      { name: 'prerequisites', label: 'Prerequisites', type: 'textarea' },
      { name: 'skills', label: 'Skills covered', type: 'textarea' },
      { name: 'career_relevance', label: 'Career relevance', type: 'textarea' },
      { name: 'related_course_id', label: 'Related course ID', type: 'number', hint: 'Optional — the numeric ID of a course from the Courses list.' },
      { name: 'publish_status', label: 'Status', type: 'select', options: ['draft', 'published'], default: 'draft' },
    ],
  },
  glossary: {
    key: 'glossary',
    label: 'Glossary',
    singular: 'Glossary term',
    apiBase: '/admin/glossary',
    api: createResourceApi('/admin/glossary'),
    permission: 'knowledge.manage',
    titleField: 'term',
    columns: [
      { key: 'term', label: 'Term' },
      { key: 'display_letter', label: 'Letter' },
      { key: 'publish_status', label: 'Status', badge: true },
    ],
    fields: [
      { name: 'term', label: 'Term', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', hint: 'Leave blank to auto-generate from the term.' },
      { name: 'definition', label: 'Definition', type: 'textarea', required: true },
      { name: 'display_letter', label: 'A-Z nav letter', type: 'text', hint: 'Leave blank to use the term’s first letter.', maxLength: 1 },
      { name: 'related_knowledge_content_id', label: 'Related article ID', type: 'number', hint: 'Optional — the numeric ID of a Knowledge Center article.' },
      { name: 'publish_status', label: 'Status', type: 'select', options: ['draft', 'published'], default: 'draft' },
    ],
  },
  testimonials: {
    key: 'testimonials',
    label: 'Testimonials',
    singular: 'Testimonial',
    apiBase: '/admin/testimonials',
    api: createResourceApi('/admin/testimonials'),
    permission: 'testimonials.manage',
    titleField: 'student_name',
    columns: [
      { key: 'student_name', label: 'Student' },
      { key: 'batch_year', label: 'Batch' },
      { key: 'publish_status', label: 'Status', badge: true },
    ],
    fields: [
      { name: 'student_name', label: 'Student name', type: 'text', required: true },
      { name: 'quote', label: 'Quote', type: 'textarea', required: true },
      { name: 'course_id', label: 'Course ID', type: 'number', hint: 'Optional — the numeric ID of the related course.' },
      { name: 'batch_year', label: 'Batch year', type: 'text' },
      { name: 'designation', label: 'Designation', type: 'text' },
      { name: 'photo_media_id', label: 'Photo (media ID)', type: 'number', hint: 'Upload the photo in Media Library first, then paste its ID here.' },
      { name: 'display_order', label: 'Display order', type: 'number', default: 0 },
      { name: 'publish_status', label: 'Status', type: 'select', options: ['draft', 'published'], default: 'draft' },
    ],
  },
  team: {
    key: 'team',
    label: 'Leadership & Faculty',
    singular: 'Team member',
    apiBase: '/admin/team',
    api: createResourceApi('/admin/team'),
    permission: 'testimonials.manage',
    titleField: 'name',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'category', label: 'Category' },
      { key: 'publish_status', label: 'Status', badge: true },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'designation', label: 'Designation', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'select', options: ['leadership', 'faculty', 'industry_mentor'], default: 'faculty' },
      { name: 'biography', label: 'Biography', type: 'textarea' },
      { name: 'expertise', label: 'Areas of expertise', type: 'text' },
      { name: 'certifications', label: 'Certifications held', type: 'text' },
      { name: 'experience_years', label: 'Years of experience', type: 'number' },
      { name: 'social_link', label: 'Social / LinkedIn link', type: 'text' },
      { name: 'photo_media_id', label: 'Photo (media ID)', type: 'number', hint: 'Upload the photo in Media Library first, then paste its ID here.' },
      { name: 'display_order', label: 'Display order', type: 'number', default: 0 },
      { name: 'publish_status', label: 'Status', type: 'select', options: ['draft', 'published'], default: 'draft' },
    ],
  },
  faqs: {
    key: 'faqs',
    label: 'FAQs',
    singular: 'FAQ',
    apiBase: '/admin/faqs',
    api: createResourceApi('/admin/faqs'),
    permission: 'faqs.manage',
    titleField: 'question',
    columns: [
      { key: 'question', label: 'Question' },
      { key: 'category', label: 'Category' },
      { key: 'publish_status', label: 'Status', badge: true },
    ],
    fields: [
      { name: 'question', label: 'Question', type: 'text', required: true },
      { name: 'answer', label: 'Answer', type: 'textarea', required: true },
      {
        name: 'category',
        label: 'Category',
        type: 'select',
        options: ['courses', 'admissions', 'classroom_training', 'certifications', 'careers', 'placements', 'knowledge_center'],
        default: 'courses',
      },
      { name: 'display_order', label: 'Display order', type: 'number', default: 0 },
      { name: 'publish_status', label: 'Status', type: 'select', options: ['draft', 'published'], default: 'draft' },
    ],
  },
  events: {
    key: 'events',
    label: 'Events & Workshops',
    singular: 'Event',
    apiBase: '/admin/events',
    api: createResourceApi('/admin/events'),
    permission: 'events.manage',
    titleField: 'title',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'type', label: 'Type' },
      { key: 'start_date', label: 'Starts' },
      { key: 'publish_status', label: 'Status', badge: true },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', hint: 'Leave blank to auto-generate from the title.' },
      { name: 'type', label: 'Type', type: 'select', options: ['event', 'workshop', 'webinar'], default: 'event' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'start_date', label: 'Start date/time', type: 'datetime-local' },
      { name: 'end_date', label: 'End date/time', type: 'datetime-local' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'is_online', label: 'This is an online event', type: 'checkbox' },
      { name: 'registration_link', label: 'Registration link', type: 'text' },
      { name: 'featured_image_id', label: 'Featured image (media ID)', type: 'number' },
      { name: 'publish_status', label: 'Status', type: 'select', options: ['draft', 'published'], default: 'draft' },
    ],
  },
  resources: {
    key: 'resources',
    label: 'Resources',
    singular: 'Resource',
    apiBase: '/admin/resources',
    api: createResourceApi('/admin/resources'),
    permission: 'events.manage',
    titleField: 'title',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'type', label: 'Type' },
      { key: 'publish_status', label: 'Status', badge: true },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', hint: 'Leave blank to auto-generate from the title.' },
      { name: 'type', label: 'Type', type: 'text', hint: 'e.g. Whitepaper, Checklist' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'file_media_id', label: 'File (media ID)', type: 'number', hint: 'Upload the file in Media Library first, then paste its ID here.' },
      { name: 'external_link', label: 'External link', type: 'text' },
      { name: 'publish_status', label: 'Status', type: 'select', options: ['draft', 'published'], default: 'draft' },
    ],
  },
}

export function getResourceConfig(key) {
  const config = RESOURCE_CONFIGS[key]
  if (!config) throw new Error(`Unknown admin resource: ${key}`)
  return config
}
